package com.wilmss.PrayerRequestJournal.domain.entities;
// Generated Apr 10, 2012 3:29:31 PM by Hibernate Tools 3.2.1.GA

import com.wilmss.PrayerRequestJournal.domain.interfaces.IDisposition;


/**
 * PrayerResponse generated by hbm2java
 */
public class Disposition  implements IDisposition{

     private int dispositionId;
     private String disposition;

    public Disposition() {
    }

    public Disposition(int dispositionId, String disposition) {
       this.dispositionId = dispositionId;
       this.disposition = disposition;
    }

    @Override
    public int getDispositionId() {
        return this.dispositionId;
    }
    
    @Override
    public void setDispositionId(int dispositionId) {
        this.dispositionId = dispositionId;
    }
    
    @Override
    public String getDisposition() {
        return this.disposition;
    }
    
    @Override
    public void setDisposition(String disposition) {
        this.disposition = disposition;
    }
}


