package com.wilmss.PrayerRequestJournal.domain.entities;
// Generated Apr 10, 2012 3:29:31 PM by Hibernate Tools 3.2.1.GA


import com.wilmss.PrayerRequestJournal.domain.interfaces.IPrayerResponse;
import java.util.Date;

/**
 * PrayerResponse generated by hbm2java
 */
public class PrayerResponse  implements java.io.Serializable, IPrayerResponse {


     private int responseId;
     private int requestId;
     private String detail;
     private String disposition;
     private Date responseDate;
     private Date responseTime;

    public PrayerResponse() {
    }

    public PrayerResponse(int responseId, int requestId, String detail, String disposition, Date responseDate, Date responseTime) {
       this.responseId = responseId;
       this.requestId = requestId;
       this.detail = detail;
       this.disposition = disposition;
       this.responseDate = responseDate;
       this.responseTime = responseTime;
    }
   
    @Override
    public int getResponseId() {
        return this.responseId;
    }
    
    @Override
    public void setResponseId(int responseId) {
        this.responseId = responseId;
    }
    @Override
    public int getRequestId() {
        return this.requestId;
    }
    
    @Override
    public void setRequestId(int requestId) {
        this.requestId = requestId;
    }
    @Override
    public String getDetail() {
        return this.detail;
    }
    
    @Override
    public void setDetail(String detail) {
        this.detail = detail;
    }
    @Override
    public String getDisposition() {
        return this.disposition;
    }
    
    @Override
    public void setDisposition(String disposition) {
        this.disposition = disposition;
    }
    @Override
    public Date getResponseDate() {
        return this.responseDate;
    }
    
    @Override
    public void setResponseDate(Date responseDate) {
        this.responseDate = responseDate;
    }
    @Override
    public Date getResponseTime() {
        return this.responseTime;
    }
    
    @Override
    public void setResponseTime(Date responseTime) {
        this.responseTime = responseTime;
    }




}


