package com.wilmss.PrayerRequestJournal.domain.entities;
// Generated Apr 10, 2012 3:29:31 PM by Hibernate Tools 3.2.1.GA


import com.wilmss.PrayerRequestJournal.domain.interfaces.IPrayerRequest;
import com.wilmss.PrayerRequestJournal.domain.interfaces.IPrayerRequestor;

import java.util.Date;

/**
 * PrayerRequest generated by hbm2java
 */
public class PrayerRequest  implements java.io.Serializable, IPrayerRequest {


     private int requestId;
     private int requestorId;
     private String request;
     private Date requestDate;
     private Date requestTime;
     private String title;
     private IPrayerRequestor prayerRequestor;

    public PrayerRequest() {
    }

	
    public PrayerRequest(int requestId, int requestorId, String request, Date requestDate, Date requestTime) {
        this.requestId = requestId;
        this.requestorId = requestorId;
        this.request = request;
        this.requestDate = requestDate;
        this.requestTime = requestTime;
    }
    public PrayerRequest(int requestId, int requestorId, String request, Date requestDate, Date requestTime, String title) {
       this.requestId = requestId;
       this.requestorId = requestorId;
       this.request = request;
       this.requestDate = requestDate;
       this.requestTime = requestTime;
       this.title = title;
    }
   
    @Override
    public int getRequestId() {
        return this.requestId;
    }
    
    @Override
    public void setRequestId(int requestId) {
        this.requestId = requestId;
    }
    @Override
    public int getRequestorId() {
        return this.requestorId;
    }
    
    @Override
    public void setRequestorId(int requestorId) {
        this.requestorId = requestorId;
    }
    @Override
    public String getRequest() {
        return this.request;
    }
    
    @Override
    public void setRequest(String request) {
        this.request = request;
    }
    @Override
    public Date getRequestDate() {
        return this.requestDate;
    }
    
    @Override
    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }
    @Override
    public Date getRequestTime() {
        return this.requestTime;
    }
    
    @Override
    public void setRequestTime(Date requestTime) {
        this.requestTime = requestTime;
    }
    @Override
    public String getTitle() {
        return this.title;
    }
    
    @Override
    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public void setPrayerRequestor(IPrayerRequestor requestor){
        this.prayerRequestor = requestor;
    }
    
    @Override
    public IPrayerRequestor getPrayerRequestor() {
        return this.prayerRequestor;
    }
}


