package com.wilmss.PrayerRequestJournal.domain.entities;
// Generated Apr 10, 2012 3:29:31 PM by Hibernate Tools 3.2.1.GA


import com.wilmss.PrayerRequestJournal.domain.interfaces.IPrayerRequest;
import com.wilmss.PrayerRequestJournal.domain.interfaces.IPrayerRequestor;
import java.util.Date;
import java.util.List;
import java.util.Set;

/**
 * PrayerRequestor generated by hbm2java
 */
public class PrayerRequestor  implements java.io.Serializable, IPrayerRequestor {

     private int requestorId;
     private String name;
     private String email;
     private String password;
     private Date lastLogonDate;
     private Date lastLogonTime;
     private Integer isactive;
     private Integer isadmin;
     private String userName;
     private Set<IPrayerRequest> requests;
     
    public PrayerRequestor() {
    }
    
    public PrayerRequestor(int requestorId, String name, String email, String password, String userName) {
        this.requestorId = requestorId;
        this.name = name;
        this.email = email;
        this.password = password;
        this.userName = userName;
    }
    
    public PrayerRequestor(int requestorId, String name, String email, String password, Date lastLogonDate, Date lastLogonTime, Integer isactive, Integer isadmin, String userName) {
       this.requestorId = requestorId;
       this.name = name;
       this.email = email;
       this.password = password;
       this.lastLogonDate = lastLogonDate;
       this.lastLogonTime = lastLogonTime;
       this.isactive = isactive;
       this.isadmin = isadmin;
       this.userName = userName;
    }
    
    @Override
    public void setUsername(String userName){
        this.userName = userName;
    }
    
    @Override
    public String getUsername(){
        return this.userName;
    }
    
    @Override
    public int getRequestorId() {
        return this.requestorId;
    }
    
    @Override
    public void setRequestorId(int requestorId) {
        this.requestorId = requestorId;
    }
    @Override
    public String getName() {
        return this.name;
    }
    
    @Override
    public void setName(String name) {
        this.name = name;
    }
    @Override
    public String getEmail() {
        return this.email;
    }
    
    @Override
    public void setEmail(String email) {
        this.email = email;
    }
    @Override
    public String getPassword() {
        return this.password;
    }
    
    @Override
    public void setPassword(String password) {
        this.password = password;
    }
    @Override
    public Date getLastLogonDate() {
        return this.lastLogonDate;
    }
    
    @Override
    public void setLastLogonDate(Date lastLogonDate) {
        this.lastLogonDate = lastLogonDate;
    }
    @Override
    public Date getLastLogonTime() {
        return this.lastLogonTime;
    }
    
    @Override
    public void setLastLogonTime(Date lastLogonTime) {
        this.lastLogonTime = lastLogonTime;
    }
    @Override
    public Integer getIsactive() {
        return this.isactive;
    }
    
    @Override
    public void setIsactive(Integer isactive) {
        this.isactive = isactive;
    }
    @Override
    public Integer getIsadmin() {
        return this.isadmin;
    }
    
    @Override
    public void setIsadmin(Integer isadmin) {
        this.isadmin = isadmin;
    }

    @Override
    public void setRequests(Set<IPrayerRequest> requests) {
        this.requests=requests;
    }

    @Override
    public Set<IPrayerRequest> getRequests() {
        return requests;
    }
}


